import { GraphicDesign, WebProject, Client, Skill, ShowreelVideo } from './sanity.types';

// Mock Graphic Design Projects
export const mockGraphicDesigns = [
  {
    _id: '1',
    title: 'Angama Assessment Project',
    slug: { current: 'angama-assessment', _type: 'slug' },
    mainImage: '/portfolio/graphic/Angama_Assessment_Nkosi/1.jpg' as any,
    vimeoUrl: 'https://vimeo.com/1140274315',
    gallery: [
      '/portfolio/graphic/Angama_Assessment_Nkosi/2.jpg',
      '/portfolio/graphic/Angama_Assessment_Nkosi/3.jpg',
      '/portfolio/graphic/Angama_Assessment_Nkosi/4.jpg',
      '/portfolio/graphic/Angama_Assessment_Nkosi/5.jpg',
      '/portfolio/graphic/Angama_Assessment_Nkosi/6.jpg',
      '/portfolio/graphic/Angama_Assessment_Nkosi/7.jpg',
      '/portfolio/graphic/Angama_Assessment_Nkosi/8.jpg',
      '/portfolio/graphic/Angama_Assessment_Nkosi/9.jpg',
      '/portfolio/graphic/Angama_Assessment_Nkosi/10.jpg',
    ] as any,
    category: 'branding',
    description: 'Comprehensive brand identity and assessment project featuring modern design principles',
    client: 'Angama',
    year: 2024,
    featured: true,
    order: 1,
  },
  {
    _id: '2',
    title: 'Vertex Design Project',
    slug: { current: 'vertex-design', _type: 'slug' },
    mainImage: '/portfolio/graphic/Vertex_Nkosi/1.jpg' as any,
    gallery: [
      '/portfolio/graphic/Vertex_Nkosi/2.jpg',
      '/portfolio/graphic/Vertex_Nkosi/3.jpg',
      '/portfolio/graphic/Vertex_Nkosi/4.jpg',
      '/portfolio/graphic/Vertex_Nkosi/5.jpg',
      '/portfolio/graphic/Vertex_Nkosi/6.jpg',
      '/portfolio/graphic/Vertex_Nkosi/7.jpg',
      '/portfolio/graphic/Vertex_Nkosi/8.jpg',
    ] as any,
    category: 'branding',
    description: 'Modern brand identity design with clean lines and contemporary aesthetics',
    client: 'Vertex',
    year: 2024,
    featured: true,
    order: 2,
  },
  {
    _id: '3',
    title: 'My Soul Knows - Book Design',
    slug: { current: 'my-soul-knows-book', _type: 'slug' },
    mainImage: '/portfolio/graphic/My Soul Knows Book/18.jpg' as any,
    gallery: [
      '/portfolio/graphic/My Soul Knows Book/19.jpg',
    ] as any,
    category: 'print',
    description: 'Book cover and layout design featuring elegant typography and spiritual themes',
    year: 2024,
    featured: false,
    order: 3,
  },
  {
    _id: '4',
    title: 'Electrocom X Campaign',
    slug: { current: 'electrocom-x', _type: 'slug' },
    mainImage: '/portfolio/graphic/X Submission/Electrocom X/1.jpg' as any,
    gallery: [
      '/portfolio/graphic/X Submission/Electrocom X/2.jpg',
      '/portfolio/graphic/X Submission/Electrocom X/3.jpg',
      '/portfolio/graphic/X Submission/Electrocom X/4.jpg',
      '/portfolio/graphic/X Submission/Electrocom X/5.jpg',
      '/portfolio/graphic/X Submission/Electrocom X/6.jpg',
      '/portfolio/graphic/X Submission/Electrocom X/7.jpg',
      '/portfolio/graphic/X Submission/Electrocom X/8.jpg',
    ] as any,
    category: 'social',
    description: 'Social media campaign design for Electrocom with bold visuals and engaging content',
    client: 'Electrocom',
    year: 2024,
    featured: true,
    order: 4,
  },
  {
    _id: '5',
    title: 'X Submission Portfolio',
    slug: { current: 'x-submission', _type: 'slug' },
    mainImage: '/portfolio/graphic/X Submission/1.jpg' as any,
    gallery: [
      '/portfolio/graphic/X Submission/2.jpg',
      '/portfolio/graphic/X Submission/3.jpg',
      '/portfolio/graphic/X Submission/4.jpg',
      '/portfolio/graphic/X Submission/5.jpg',
      '/portfolio/graphic/X Submission/6.jpg',
      '/portfolio/graphic/X Submission/7.jpg',
      '/portfolio/graphic/X Submission/8.jpg',
      '/portfolio/graphic/X Submission/9.jpg',
      '/portfolio/graphic/X Submission/10.jpg',
    ] as any,
    category: 'uiux',
    description: 'Diverse portfolio submission showcasing various design styles and techniques',
    year: 2024,
    featured: false,
    order: 5,
  },
];

// Mock Web Projects
export const mockWebProjects = [
  {
    _id: 'web1',
    title: 'ProTenders South Africa',
    slug: { current: 'protenders', _type: 'slug' },
    description: 'Comprehensive government tenders platform connecting businesses with over 48,000 tender opportunities across South Africa. Built with modern web technologies and optimized user experience.',
    mainImage: '/portfolio/website/ProTenders.co.za/Screenshot 2025-11-24 at 14-16-08 Government Tenders South Africa 48 000 Opportunities ProTenders.png' as any,
    gallery: [
      '/portfolio/website/ProTenders.co.za/Screenshot 2025-11-24 at 14-16-20 Government Tenders South Africa 48 000 Opportunities ProTenders.png',
      '/portfolio/website/ProTenders.co.za/Screenshot 2025-11-24 at 14-16-33 Government Tenders South Africa 48 000 Opportunities ProTenders.png',
    ] as any,
    liveUrl: 'https://protenders.co.za',
    technologies: ['WordPress', 'PHP', 'MySQL', 'JavaScript', 'Custom API Integration'],
    category: 'webapp',
    client: 'ProTenders',
    year: 2024,
    featured: true,
    order: 1,
  },
];

// Mock Clients
export const mockClients = [
  {
    _id: 'client1',
    name: 'Angama',
    logo: '/portfolio/graphic/Angama_Assessment_Nkosi/1.jpg' as any,
    order: 1,
  },
  {
    _id: 'client2',
    name: 'Vertex',
    logo: '/portfolio/graphic/Vertex_Nkosi/1.jpg' as any,
    order: 2,
  },
  {
    _id: 'client3',
    name: 'Electrocom',
    logo: '/portfolio/graphic/X Submission/Electrocom X/1.jpg' as any,
    order: 3,
  },
  {
    _id: 'client4',
    name: 'ProTenders',
    logo: '/portfolio/website/ProTenders.co.za/Screenshot 2025-11-24 at 14-16-08 Government Tenders South Africa 48 000 Opportunities ProTenders.png' as any,
    website: 'https://protenders.co.za',
    testimonial: 'NEDESIGNS delivered an exceptional platform that has transformed how businesses access tender opportunities in South Africa.',
    role: 'CEO',
    order: 4,
  },
];

// Mock Skills
export const mockSkills = [
  {
    _id: 'skill1',
    name: 'WordPress',
    icon: '/logos/wordpress-icon-seeklogo.png' as any,
    category: 'development',
    proficiency: 'expert',
    order: 1,
  },
  {
    _id: 'skill2',
    name: 'WooCommerce',
    icon: '/logos/woocommerce-seeklogo.png' as any,
    category: 'plugins',
    proficiency: 'expert',
    order: 2,
  },
  {
    _id: 'skill3',
    name: 'Shopify',
    icon: '/logos/shopify-seeklogo.png' as any,
    category: 'development',
    proficiency: 'advanced',
    order: 3,
  },
  {
    _id: 'skill4',
    name: 'MemberPress',
    icon: '/logos/memberpress-seeklogo.png' as any,
    category: 'plugins',
    proficiency: 'advanced',
    order: 4,
  },
  {
    _id: 'skill5',
    name: 'Adobe Photoshop',
    category: 'design',
    proficiency: 'expert',
    order: 5,
  },
  {
    _id: 'skill6',
    name: 'Adobe Illustrator',
    category: 'design',
    proficiency: 'expert',
    order: 6,
  },
  {
    _id: 'skill7',
    name: 'Figma',
    category: 'design',
    proficiency: 'advanced',
    order: 7,
  },
  {
    _id: 'skill8',
    name: 'React',
    category: 'frameworks',
    proficiency: 'advanced',
    order: 8,
  },
  {
    _id: 'skill9',
    name: 'Next.js',
    category: 'frameworks',
    proficiency: 'advanced',
    order: 9,
  },
  {
    _id: 'skill10',
    name: 'TypeScript',
    category: 'development',
    proficiency: 'advanced',
    order: 10,
  },
];

// Mock Showreel Videos
export const mockShowreelVideos = [
  {
    _id: 'showreel1',
    title: 'Angama Motion Reel',
    vimeoUrl: 'https://vimeo.com/1140274315',
    order: 1,
  },
  {
    _id: 'showreel2',
    title: 'Brand Animation Showcase',
    vimeoUrl: 'https://vimeo.com/1140274315',
    order: 2,
  },
  {
    _id: 'showreel3',
    title: 'Motion Graphics Portfolio',
    vimeoUrl: 'https://vimeo.com/1140274315',
    order: 3,
  },
  {
    _id: 'showreel4',
    title: 'Commercial Work Reel',
    vimeoUrl: 'https://vimeo.com/1140274315',
    order: 4,
  },
  {
    _id: 'showreel5',
    title: 'Logo Animation Collection',
    vimeoUrl: 'https://vimeo.com/1140274315',
    order: 5,
  },
  {
    _id: 'showreel6',
    title: 'Product Visualization',
    vimeoUrl: 'https://vimeo.com/1140274315',
    order: 6,
  },
  {
    _id: 'showreel7',
    title: 'Social Media Campaigns',
    vimeoUrl: 'https://vimeo.com/1140274315',
    order: 7,
  },
  {
    _id: 'showreel8',
    title: 'UI/UX Interactions',
    vimeoUrl: 'https://vimeo.com/1140274315',
    order: 8,
  },
  {
    _id: 'showreel9',
    title: 'Explainer Videos',
    vimeoUrl: 'https://vimeo.com/1140274315',
    order: 9,
  },
  {
    _id: 'showreel10',
    title: 'Creative Showreel 2024',
    vimeoUrl: 'https://vimeo.com/1140274315',
    order: 10,
  },
];
